<a href="https://colab.research.google.com/github/javeddd12/LAB-TASK/blob/main/Copy_of_SIM_day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
diag_elements = np.diag(A)
D = np.diag([1, 2, 3])
Anti_Dia = np.fliplr(D)
U = np.triu(A)
L = np.triu(A)
R = np.random.rand(3, 3)

print("\n",D,"\n")
print("Diagonal Elements: \n",diag_elements,"\n")
print("Anti Diagonal: \n",Anti_Dia,"\n")
print("Upper Triangle: \n",U,"\n")
print("Lower Triangle: \n",L,"\n")
print("Random point: \n",R,"\n")




 [[1 0 0]
 [0 2 0]
 [0 0 3]] 

Diagonal Elements: 
 [1 5 9] 

Anti Diagonal: 
 [[0 0 1]
 [0 2 0]
 [3 0 0]] 

Upper Triangle: 
 [[1 2 3]
 [0 5 6]
 [0 0 9]] 

Lower Triangle: 
 [[1 2 3]
 [0 5 6]
 [0 0 9]] 

Random point: 
 [[0.22071781 0.74399922 0.8167596 ]
 [0.29232924 0.13792287 0.63086762]
 [0.65529634 0.56521874 0.3325038 ]] 



In [ ]:
A = np.array([[1, 2],[3, 4]])
size_A = A.shape
det_A = np.linalg.det(A)
if np.linalg.det(A) != 0:
  inv_A = np.linalg.inv(A)
else:
  inv_A = "Matrix is singular,cannot compute "

rank_A = np.linalg.matrix_rank(A)
eigenvalues, eigenvector = np.linalg.eig(A)
char_poly = np.poly(A)
root = np.roots(char_poly)


print("Size of Matrix: \n",size_A,"\n")
print("Determinant: \n",det_A, "\n")
print("Inverse Matrix: \n",inv_A,"\n")
print("Rank of Matrix: \n",rank_A,"\n")
print("Eigenvalues of A: \n",eigenvalues,"\n")
print("Eigenvector of A: \n",eigenvector,"\n")
print("Charectaristic polynomial: \n",char_poly,"\n")
print("Root of polynomial: \n",root,"\n")



Size of Matrix: 
 (2, 2) 

Determinant: 
 -2.0000000000000004 

Inverse Matrix: 
 [[-2.   1. ]
 [ 1.5 -0.5]] 

Rank of Matrix: 
 2 

Eigenvalues of A: 
 [-0.37228132  5.37228132] 

Eigenvector of A: 
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]] 

Charectaristic polynomial: 
 [ 1. -5. -2.] 

Root of polynomial: 
 [ 5.37228132 -0.37228132] 

